name: Build JAR with Ant

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Install Ant
        run: sudo apt-get update && sudo apt-get install -y ant

      - name: Build JAR
        run: ant jar

