name: Docker Build and Push

on:
  push:
    branches:
      - main  # Change this to the branch where you want the action to trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK  # If Java is not already set up
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Specify the desired Java version

      - name: Build JAR
        run: ant  # Assuming you have the 'build.xml' file in the repository root

      - name: Set up Docker
        uses: varatharamanujam/java-cicd-githubaction

      - name: Build Docker image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: your-docker-username/your-docker-image-name:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


